services:
  downloader:
    build:
      context: .
    image: cancer
    command:
      - download
    volumes:
      - downloads:/data
    environment:
      STORAGE_DIR: /data
    env_file:
      - .env

  updater:
    build:
      context: .
    image: cancer
    command:
      - handle_updates
    env_file:
      - .env

volumes:
  downloads:
