[tool.poetry]
name = "cancerbot"
description = "Cures cancer"
version = "1.0.0"
authors = ["OpenAlcoholics <team@openalcoholics.group>"]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.11"
click = "^8.0.0"
google-cloud-pubsub = "^2.0.0"
Pillow = "^9.0.0"
requests = "2.28.2"
sentry-sdk = "1.14.0"
yt-dlp = "2023.1.6"

[tool.poetry.dev-dependencies]
black = "^22.0.0"
flake8 = "^6.0.0"
mypy = "0.991"
types-requests = "2.28.11.8"
types-Pillow = "^9.0.0"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"

[[tool.mypy.overrides]]
module = "google.cloud.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module="yt_dlp.*"
ignore_missing_imports = true
