[tool.poetry]
name = "cancerbot"
description = "Cures cancer"
version = "1.0.0"
authors = ["OpenAlcoholics <team@openalcoholics.group>"]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.10"
click = "^8.0.0"
google-cloud-pubsub = "^2.0.0"
paho-mqtt = "^1.0.0"
pika = "^1.0.0"
Pillow = "^9.0.0"
requests = "2.28.1"
sentry-sdk = "1.9.9"
yt-dlp = "2022.9.1"

[tool.poetry.dev-dependencies]
black = "^22.0.0"
flake8 = "^5.0.0"
mypy = "0.981"
types-requests = "2.28.11"
types-pika = "1.2.0b1"
types-Pillow = "^9.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.mypy.overrides]]
module = "google.cloud.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module="paho.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module="yt_dlp.*"
ignore_missing_imports = true
