[project]
requires-python = "==3.12.*"

[tool.poetry]
name = "cancerbot"
description = "Cures cancer"
version = "1.0.0"
authors = ["OpenAlcoholics <team@openalcoholics.group>"]
license = "MIT"
packages = [
    { include = "cancer", from = "src" }
]

[tool.poetry.dependencies]
python = "~3.12"
click = "^8.0.0"
google-cloud-pubsub = "^2.0.0"
httpx = "^0.27.0"
Pillow = "^10.0.0"
sentry-sdk = "^2.0.0"
yt-dlp = "2023.07.06"

[tool.poetry.group.dev.dependencies]
mypy = "~1.12"
pytest = "^8.0.0"
ruff = "0.7.0"
types-requests = "^2.28.11"
types-Pillow = "^9.0.0"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"

[[tool.mypy.overrides]]
module = "google.cloud.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "yt_dlp.*"
ignore_missing_imports = true

[tool.ruff.lint]
select = [
    "E4",
    "E7",
    "E9",
    "F",
    "FURB",
    "G",
    "I001",
    "LOG",
    "PTH",
    "Q",
    "UP",
]
ignore = [
    # redundant-open-modes
    "UP015",
]
