---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: insta
spec:
  secretStoreRef:
    name: doppler-prep
    kind: ClusterSecretStore
  target:
    name: cancer-secrets
  dataFrom:
    - find:
        path: "CANCER_INSTA_"
    - rewrite:
        - regexp:
            source: "CANCER_INSTA_(.+)"
            target: "$1"
