{{ if has "insta_download" .Values.features  }}
---
apiVersion: v1
kind: Service
metadata:
  name: cancer-insta
spec:
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cancer-insta-downloader
spec:
  revisionHistoryLimit: 1
  serviceName: cancer-insta
  selector:
    matchLabels:
      app: insta-downloader
  replicas: 1
  volumeClaimTemplates:
    - apiVersion: v1
      kind:
        PersistentVolumeClaim
      metadata:
        name: cookie-jar
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      labels:
        app: insta-downloader
    spec:
      securityContext:
        fsGroup: 500
      containers:
        - name: app
          image: {{ .Values.image }}:{{ .Values.appVersion }}
          args:
            - download
          resources:
            limits:
              cpu: "2"
            requests:
              cpu: 50m
              memory: 128Mi
          env:
            - name: STORAGE_DIR
              value: "/downloads"
            - name: DOWNLOAD_TYPE
              value: insta
            - name: COOKIE_FILE
              value: /cookies/insta-cookies.dat
          envFrom:
            - configMapRef:
                name: cancer-config
            - secretRef:
                name: cancer-secrets
          volumeMounts:
{{ include "secrets.volumeMount" . | indent 12 }}
            - mountPath: "/downloads"
              name: downloads
            - mountPath: "/cookies"
              name: cookie-jar
            - mountPath: "/static-cookies"
              name: cookie
      volumes:
{{ include "secrets.volume" . | indent 8 }}
        - name: downloads
          emptyDir: { }
        - name: cookie
          secret:
            secretName: insta
            items:
              - key: COOKIES
                path: insta-cookies.dat
{{ end }}
