---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cancer-secrets
spec:
  secretStoreRef:
    name: doppler-prep
    kind: ClusterSecretStore
  target:
    name: cancer-secrets
  dataFrom:
    - find:
        path: "CANCER_BASE_"
      rewrite:
        - regexp:
            source: "CANCER_BASE_(.+)"
            target: "$1"
