---
{{ if has "telegram_audio_convert" .Values.features  }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cancer-telegram-audio-converter
spec:
  revisionHistoryLimit: 0
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: telegram-audio-converter
  template:
    metadata:
      labels:
        app: telegram-audio-converter
    spec:
      serviceAccountName: cancer
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 1000
      volumes:
{{ include "secrets.volume" . | indent 8 }}
      containers:
        - name: app
          image: {{ .Values.image }}:{{ .Values.appVersion }}
          args:
            - telegram_audio_convert
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          resources:
            limits:
              cpu: 20m
            requests:
              cpu: 10m
              memory: 16Mi
          envFrom:
            - configMapRef:
                name: cancer-config
            - secretRef:
                name: cancer-secrets
          volumeMounts:
{{ include "secrets.volumeMount" . | indent 12 }}
{{ end }}
