---
{{ if has "tiktok_download" .Values.features  }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cancer-tiktok-downloader
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: tiktok-downloader
  template:
    metadata:
      labels:
        app: tiktok-downloader
    spec:
      serviceAccountName: cancer
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 1000
      containers:
        - name: app
          image: {{ .Values.image }}:{{ .Values.appVersion }}
          args:
            - download
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          resources:
            limits:
              cpu: 800m
            requests:
              cpu: 50m
              memory: 128Mi
          env:
            - name: STORAGE_DIR
              value: "/downloads"
            - name: DOWNLOAD_TYPE
              value: tiktok
          envFrom:
            - configMapRef:
                name: cancer-config
            - secretRef:
                name: cancer-secrets
          volumeMounts:
{{ include "secrets.volumeMount" . | indent 12 }}
            - mountPath: "/downloads"
              name: downloads
      volumes:
        - {{ include "downloads.volume" $ | fromYaml | toJson }}
        - {{ include "secrets.volume" $ | fromYaml | toJson }}
{{ end }}
