---
{{ if has "download" .Values.features  }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cancer-downloader
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: downloader
  template:
    metadata:
      labels:
        app: downloader
    spec:
      containers:
        - name: app
          image: {{ .Values.image }}
          args:
            - download
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: 50m
              memory: 128Mi
          env:
            - name: STORAGE_DIR
              value: "/downloads"
          envFrom:
            - configMapRef:
                name: cancer-config
            - secretRef:
                name: cancer-secrets
          volumeMounts:
            - mountPath: "/downloads"
              name: downloads
      volumes:
        - name: downloads
          emptyDir: { }
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: cancer-downloader
spec:
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cancer-downloader
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
{{ end }}
