apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-client
  template:
    metadata:
      labels:
        app: mqtt-client
    spec:
      containers:
        - name: client
          image: efrecon/mqtt-client
          command: [ "sub" ]
          args: [
              "-h", "$(MQTT_HOST)",
              "-t", "#",
              "-u", "$(MQTT_USER)",
              "-P", "$(MQTT_PASSWORD)",
              "-v",
              "-d"
          ]
          envFrom:
            - configMapRef:
                name: config
          env:
            - name: MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MQTT_PASSWORD
                  name: secrets
