apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cancer-secrets
data:
  GSA_JSON: "{{ .Values.gcp.gsaJson }}"
stringData:
  RABBITMQ_PASSWORD: {{ .Values.rabbit.password }}
  SENTRY_DSN: "{{ .Values.sentry.dsn }}"
  TELEGRAM_API_KEY: {{ .Values.telegram.apiKey }}
