---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: telegram-bots
  name: vreddit-update-handler
  labels:
    app: vreddit-update-handler
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vreddit-update-handler
  template:
    metadata:
      labels:
        app: vreddit-update-handler
    spec:
      containers:
        - name: app
          image: {{ .Values.image }}
          resources:
            limits:
              cpu: 400m
            requests:
              cpu: 50m
              memory: 256Mi
          env:
            - name: STORAGE_DIR
              value: "/downloads"
          envFrom:
            - secretRef:
                name: vreddit-secrets
          volumeMounts:
            - mountPath: "/downloads"
              name: downloads
      volumes:
        - name: downloads
          emptyDir: {}
