---
{{ if has "handle_updates" .Values.features  }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cancer-update-handler
spec:
  revisionHistoryLimit: 1
  replicas: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: update-handler
  template:
    metadata:
      labels:
        app: update-handler
    spec:
      containers:
        - name: app
          image: {{ .Values.image }}
          args:
            - handle_updates
          resources:
            limits:
              cpu: 20m
            requests:
              cpu: 5m
              memory: 32Mi
          envFrom:
            - configMapRef:
                name: cancer-config
            - secretRef:
                name: cancer-secrets
{{end}}
