---
{{ if has "youtube_download" .Values.features  }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cancer-youtube-downloader
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: youtube-downloader
  template:
    metadata:
      labels:
        app: youtube-downloader
    spec:
      terminationGracePeriodSeconds: 600
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "kubernetes.io/hostname"
                    operator: In
                    values:
                      - rke2-agent-0
                      - rke2-agent-1
      containers:
        - name: app
          image: {{ .Values.image }}
          args:
            - download
          resources:
            limits:
              cpu: "3"
            requests:
              cpu: 100m
              memory: 256Mi
          env:
            - name: STORAGE_DIR
              value: "/downloads"
            - name: DOWNLOAD_TYPE
              value: youtube
          envFrom:
            - configMapRef:
                name: cancer-config
            - secretRef:
                name: cancer-secrets
          volumeMounts:
            - mountPath: "/downloads"
              name: downloads
      volumes:
        - name: downloads
          emptyDir: { }
{{ end }}
