---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-converter
  labels:
    app: youtube-converter
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: youtube-converter
  template:
    metadata:
      labels:
        app: youtube-converter
    spec:
      containers:
        - name: app
          image: {{ .Values.image }}
          args:
            - youtube_url_convert
          resources:
            limits:
              cpu: 10m
            requests:
              cpu: 1m
              memory: 128Mi
          envFrom:
            - configMapRef:
                name: config
            - secretRef:
                name: secrets
