name: Workflow
on:
  push:
    branches: [ main ]
  pull_request: { }

env:
  IMAGE_NAME: ghcr.io/preparingforexams/telegram-vreddit-bot

jobs:
  validate-renovate-config:
    uses: BlindfoldedSurgery/renovate-config/.github/workflows/validate.yml@main

  lint:
    uses: BlindfoldedSurgery/actions-python/.github/workflows/lint.yml@v1
    with:
      python-version: '3.11'

  test:
    uses: BlindfoldedSurgery/actions-python/.github/workflows/test.yml@v1
    with:
      python-version: '3.11'

  build-container-image:
    needs:
      - lint
      - test
    strategy:
      matrix:
        platform: ["arm64", "amd64"]
    uses: BlindfoldedSurgery/actions-container/.github/workflows/build-image-docker.yml@v2
    with:
      digest-artifact-name: digests
      platform: "linux/${{ matrix.platform }}"
      push-image: ${{ github.ref_name == github.event.repository.default_branch }}
      tag-suffix: -${{ matrix.platform }}

  merge-container-image:
    if: success() && github.ref_name == github.event.repository.default_branch
    needs:
      - build-container-image
    uses: BlindfoldedSurgery/actions-container/.github/workflows/merge-manifests.yml@v3
    with:
      variant-digests: digests

  deploy:
    runs-on: ubuntu-latest
    needs: merge-container-image
    concurrency: production
    steps:
      - uses: actions/checkout@v4
      - name: Substitute environment variables in values.yaml
        run: "envsubst < values.yaml > values_sub.yaml && mv values_sub.yaml values.yaml"
        env:
          FEATURES: >
            [
            handle_updates,
            download,
            youtube_url_convert,
            telegram_audio_convert,
            twitter_download,
            vimeo_download,
            youtube_download
            ]
          GSA_JSON: ${{ secrets.GSA_JSON }}
          INSTA_PASSWORD: ${{secrets.INSTA_PASSWORD }}
          INSTA_USER: ${{secrets.INSTA_USER }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      - uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm upgrade cancerbot . --install --namespace=cancerbot --atomic
          kubeconfig: '${{ secrets.KUBECONFIG_RAW }}'

  deploy-home:
    needs: merge-container-image
    concurrency: production-home
    container: ghcr.io/bjoernpetersen/helm:latest
    runs-on: born-prep
    steps:
      - uses: actions/checkout@v4
      - name: Substitute environment variables in values.yaml
        run: "envsubst < values.yaml > values_sub.yaml && mv values_sub.yaml values.yaml"
        env:
          FEATURES: >
            [
            insta_download,
            tiktok_download
            ]
          GSA_JSON: ${{ secrets.GSA_JSON }}
          INSTA_PASSWORD: ${{secrets.INSTA_PASSWORD }}
          INSTA_USER: ${{secrets.INSTA_USER }}
          INSTA_COOKIES: ${{ secrets.INSTA_COOKIES }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      - uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm upgrade cancerbot . --install --namespace=cancerbot --atomic
          kubeconfig: '${{ secrets.BORN_KUBECONFIG_RAW }}'

  clean:
    runs-on: ubuntu-latest
    concurrency: cleanup
    continue-on-error: true
    needs: [ deploy, deploy-home ]
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - name: Clean up old app container images
        uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}
          package-type: container
          min-versions-to-keep: 10
