name: Workflow
on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  required-meta:
    uses: BlindfoldedSurgery/actions-meta/.github/workflows/required.yml@v1

  lint:
    uses: BlindfoldedSurgery/actions-python/.github/workflows/lint.yml@v2
    with:
      build-tool: uv
      python-version: '3.13'

  test:
    uses: BlindfoldedSurgery/actions-python/.github/workflows/test.yml@v2
    with:
      build-tool: uv
      python-version: '3.13'

  build-container-image:
    needs:
      - lint
      - test
    strategy:
      matrix:
        platform: ["arm64", "amd64"]
    uses: preparingforexams/actions-container/.github/workflows/build-image-kaniko.yml@v5
    with:
      digest-artifact-name: digests
      runner-name-build: ${{ (matrix.platform == 'arm64') && 'warp-ubuntu-2404-arm64-2x' || 'ubuntu-24.04' }}
      push-image: ${{ github.ref_name == github.event.repository.default_branch }}
      tag-suffix: -${{ matrix.platform }}

  merge-container-image:
    if: success() && github.ref_name == github.event.repository.default_branch
    needs:
      - build-container-image
    uses: preparingforexams/actions-container/.github/workflows/merge-manifests.yml@v5
    with:
      variant-digests: digests

  deploy:
    runs-on: ubuntu-24.04
    if: github.ref_name == github.event.repository.default_branch
    needs:
      - merge-container-image
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git push origin main:release

  clean:
    concurrency: cleanup
    needs: [ deploy ]
    uses: preparingforexams/actions-container/.github/workflows/clean.yml@v5
