name: Workflow
on: [ push ]

jobs:
  flake8:
    runs-on: ubuntu-latest
    container: python:3.10-slim
    steps:
      - run: pip install flake8
      - run: python -m flake8 src/
  push_docker:
    runs-on: ubuntu-latest
    needs:
      - flake8
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the tagged Docker image
        run: docker build -t ghcr.io/preparingforexams/vredditbot:${GITHUB_SHA} --build-arg "build=${GITHUB_SHA}" .
      - name: Push the tagged Docker image
        run: docker push ghcr.io/preparingforexams/vredditbot:${GITHUB_SHA}
  deploy:
    runs-on: ubuntu-latest
    needs: push_docker
    steps:
      - uses: actions/checkout@v2
      - name: Substitute environment variables in values.yaml
        run: "envsubst < values.yaml > values_sub.yaml && mv values_sub.yaml values.yaml"
        env:
          FEATURES: "[handle_updates, download, youtube_url_convert, insta_download, tiktok_download, youtube_download]"
          MQTT_PASSWORD: ${{ secrets.MQTT_PASSWORD }}
          RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade bot . --install --namespace=cancer
          kubeconfig: '${{ secrets.KUBECONFIG_RAW }}'
